<?php

use App\Http\Controllers\Ops\DeploymentShowController;
use App\Http\Controllers\Ops\SiteAppHealthController;
use App\Http\Controllers\Ops\SiteCloudflareController;
use App\Http\Controllers\Ops\SiteController;
use App\Http\Controllers\Ops\SiteCoolifyOpsController;
use App\Http\Controllers\Ops\SiteDetailController;
use App\Http\Controllers\Ops\SiteDomainController;
use App\Http\Controllers\Ops\SiteThemeController;
use Illuminate\Support\Facades\Route;

Route::get('/sites', [SiteController::class, 'index'])->name('ops.sites');
Route::get('/sites/create', [SiteController::class, 'create'])->name('ops.sites.create');
Route::post('/sites', [SiteController::class, 'store'])->name('ops.sites.store');
Route::post('/sites/bulk/compose', [SiteCoolifyOpsController::class, 'bulkMigrateCompose'])->name('ops.sites.bulk.compose');
Route::post('/sites/bulk/auto-deploy', [SiteCoolifyOpsController::class, 'bulkAutoDeploy'])->name('ops.sites.bulk.auto-deploy');
Route::post('/sites/bulk/deploy', [SiteCoolifyOpsController::class, 'bulkDeploy'])->name('ops.sites.bulk.deploy');
Route::post('/sites/bulk/follow-head', [SiteCoolifyOpsController::class, 'bulkFollowHead'])->name('ops.sites.bulk.follow-head');
Route::post('/sites/bulk/pin', [SiteCoolifyOpsController::class, 'bulkPin'])->name('ops.sites.bulk.pin');
Route::post('/sites/bulk/channel', [SiteCoolifyOpsController::class, 'bulkChannel'])->name('ops.sites.bulk.channel');
Route::get('/sites/bulk/channel', [SiteCoolifyOpsController::class, 'redirectGetBulkChannel'])->name('ops.sites.bulk.channel.get');
Route::post('/sites/bulk/sync', [SiteCoolifyOpsController::class, 'bulkSync'])->name('ops.sites.bulk.sync');
Route::get('/sites/bulk/sync', [SiteCoolifyOpsController::class, 'redirectGetBulkSync'])->name('ops.sites.bulk.sync.get');
Route::post('/sites/bulk/live-sync', [SiteCoolifyOpsController::class, 'liveSync'])->name('ops.sites.live-sync');
Route::get('/sites/bulk/live-sync', [SiteCoolifyOpsController::class, 'redirectGetLiveSync'])->name('ops.sites.live-sync.get');
Route::post('/sites/bulk/purge', [SiteCoolifyOpsController::class, 'bulkPurge'])->name('ops.sites.bulk.purge');
Route::post('/sites/{site}/compose', [SiteCoolifyOpsController::class, 'migrateCompose'])->name('ops.sites.compose');
Route::post('/sites/{site}/auto-deploy', [SiteCoolifyOpsController::class, 'autoDeploy'])->name('ops.sites.auto-deploy');
Route::post('/sites/{site}/pin', [SiteCoolifyOpsController::class, 'pin'])->name('ops.sites.pin');
Route::post('/sites/{site}/follow-head', [SiteCoolifyOpsController::class, 'followHead'])->name('ops.sites.follow-head');
Route::post('/sites/{site}/deploy', [SiteCoolifyOpsController::class, 'deploy'])->name('ops.sites.deploy');
Route::post('/sites/{site}/sync', [SiteCoolifyOpsController::class, 'sync'])->name('ops.sites.sync');
Route::get('/sites/{site}/sync', [SiteCoolifyOpsController::class, 'redirectGetSync'])->name('ops.sites.sync.get');
Route::post('/sites/{site}/live-sync', [SiteCoolifyOpsController::class, 'liveSyncOne'])->name('ops.sites.live-sync.one');
Route::get('/sites/{site}/live-sync', [SiteCoolifyOpsController::class, 'redirectGetLiveSyncOne'])->name('ops.sites.live-sync.one.get');
Route::post('/sites/{site}/activate', [SiteController::class, 'activate'])->name('ops.sites.activate');
Route::post('/sites/{site}/deactivate', [SiteController::class, 'deactivate'])->name('ops.sites.deactivate');
Route::get('/sites/{site}', SiteDetailController::class)->name('ops.sites.show');
Route::get('/sites/{site}/deployments/{deployment}', DeploymentShowController::class)
    ->scopeBindings()
    ->name('ops.sites.deployments.show');
Route::get('/sites/{site}/edit', [SiteController::class, 'edit'])->name('ops.sites.edit');
Route::put('/sites/{site}', [SiteController::class, 'update'])->name('ops.sites.update');
Route::post('/sites/{site}/provision', [SiteController::class, 'provision'])->name('ops.sites.provision');
Route::post('/sites/{site}/cloudflare/zone', [SiteCloudflareController::class, 'store'])->name('ops.sites.cloudflare.zone');
Route::post('/sites/{site}/cloudflare/dns', [SiteCloudflareController::class, 'confirmDns'])->name('ops.sites.cloudflare.dns');
Route::post('/sites/{site}/domains', [SiteDomainController::class, 'store'])->name('ops.sites.domains.store');
Route::post('/sites/{site}/channel', [SiteController::class, 'switchChannel'])->name('ops.sites.channel');
Route::post('/sites/{site}/health', [SiteController::class, 'checkHealth'])->name('ops.sites.health');
Route::post('/sites/{site}/app-health', [SiteAppHealthController::class, 'refresh'])->name('ops.sites.app-health');
Route::post('/sites/{site}/app-health/fix', [SiteAppHealthController::class, 'fix'])->name('ops.sites.app-health.fix');
Route::post('/sites/{site}/agent-secret', [SiteController::class, 'injectAgentSecret'])->name('ops.sites.agent-secret');
Route::post('/sites/{site}/mail', [SiteController::class, 'assignMail'])->name('ops.sites.mail');
Route::post('/sites/{site}/platform-mail', [SiteController::class, 'assignPlatformMail'])->name('ops.sites.platform-mail');
Route::post('/sites/{site}/mail-order', [SiteController::class, 'refreshMailOrder'])->name('ops.sites.mail-order');
Route::post('/sites/{site}/mailbox-requests/{mailboxRequest}/fulfill', [SiteController::class, 'fulfillMailboxRequest'])->name('ops.sites.mailbox-requests.fulfill');
Route::post('/sites/{site}/mailbox-requests/{mailboxRequest}/reject', [SiteController::class, 'rejectMailboxRequest'])->name('ops.sites.mailbox-requests.reject');
Route::post('/sites/{site}/themes', [SiteThemeController::class, 'assign'])->name('ops.sites.themes.assign');
Route::post('/sites/{site}/themes/{installation}/update', [SiteThemeController::class, 'update'])->name('ops.sites.themes.update');
Route::post('/sites/{site}/themes/{installation}/sync', [SiteThemeController::class, 'sync'])->name('ops.sites.themes.sync');
Route::post('/sites/{site}/themes/{installation}/activate', [SiteThemeController::class, 'activate'])->name('ops.sites.themes.activate');
Route::post('/sites/{site}/themes/{installation}/auto-update', [SiteThemeController::class, 'autoUpdate'])->name('ops.sites.themes.auto-update');
Route::delete('/sites/{site}/purge', [SiteController::class, 'purge'])->name('ops.sites.purge');
Route::delete('/sites/{site}', [SiteController::class, 'destroy'])->name('ops.sites.destroy');
